# Generated by Django 3.1.12 on 2022-04-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_auto_20191027_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='acquired_state',
            field=models.BooleanField(default=False),
        ),
    ]
